# This is a basic workflow to help you get started with Actions

name: publish-release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['main']
    paths:
      - 'short-urls/**'
      - '.github/workflows/*.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - '.gitignore'
      - 'requirements.txt'
      - 'short_urls_run.sh'
  pull_request:
    branches: ['main']
    paths:
      - 'short-urls/**'
      - '.github/workflows/*.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - '.gitignore'
      - 'requirements.txt'
      - 'short_urls_run.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "push_to_registries"
  push_to_registries:
    name: Build and Push Docker image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v3
        #with:
          #ref: 'master'
          # fetch-depth: 0 # fetch all history so multiple commits can be scanned
      # - name: TEST keycloak.json
        # run: |
          # cat ./public/keycloak.json
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Push to Docker Hub
        # uses: docker/build-push-action@v2
        # with:
          # context: .
          # push: true
          # tags: devasteam/deva-crm:latest
          # pull: true
      - name: Build the latest Docker image
        run: docker build . --pull --file Dockerfile --tag ministrbob/short-urls:latest
      - name: Push the latest Docker image
        run: docker push ministrbob/short-urls:latest
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      # result = /home/runner/work/GivinSchoolPortal/GivinSchoolPortal
      #- name: pwd
        #run: pwd

      - name: Copy run sh
        run: scp /home/runner/work/short_urls/short_urls/portalgs_run.sh prod:/home/dr/portalgs_run.sh

      - name: Run sh
        run: ssh prod '/home/dr/short_urls_run.sh'
